// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"

	"trano/internal/db"
)

type Station struct {
	StationCode       string          `json:"station_code"`
	StationName       string          `json:"station_name"`
	Zone              sql.NullString  `json:"zone"`
	Division          sql.NullString  `json:"division"`
	Address           sql.NullString  `json:"address"`
	ElevationM        sql.NullFloat64 `json:"elevation_m"`
	Lat               sql.NullFloat64 `json:"lat"`
	Lng               sql.NullFloat64 `json:"lng"`
	NumberOfPlatforms sql.NullInt64   `json:"number_of_platforms"`
	StationType       sql.NullString  `json:"station_type"`
	StationCategory   sql.NullString  `json:"station_category"`
	TrackType         sql.NullString  `json:"track_type"`
	CreatedAt         sql.NullString  `json:"created_at"`
	UpdatedAt         sql.NullString  `json:"updated_at"`
}

type Train struct {
	TrainNo          int64          `json:"train_no"`
	TrainName        string         `json:"train_name"`
	TrainType        string         `json:"train_type"`
	Zone             sql.NullString `json:"zone"`
	ReturnTrainNo    sql.NullInt64  `json:"return_train_no"`
	Coachcomposition sql.NullString `json:"coachcomposition"`
	SourceUrl        string         `json:"source_url"`
	CreatedAt        sql.NullString `json:"created_at"`
	UpdatedAt        sql.NullString `json:"updated_at"`
}

type TrainRoute struct {
	ScheduleID               int64   `json:"schedule_id"`
	StationCode              string  `json:"station_code"`
	DistanceKm               float64 `json:"distance_km"`
	SchArrivalMinFromStart   int64   `json:"sch_arrival_min_from_start"`
	SchDepartureMinFromStart int64   `json:"sch_departure_min_from_start"`
	Stops                    int64   `json:"stops"`
}

type TrainRouteGeometry struct {
	ScheduleID int64  `json:"schedule_id"`
	RouteGeom  []byte `json:"route_geom"`
}

type TrainRun struct {
	RunID                  string         `json:"run_id"`
	ScheduleID             int64          `json:"schedule_id"`
	TrainNo                int64          `json:"train_no"`
	RunDate                string         `json:"run_date"`
	HasStarted             int64          `json:"has_started"`
	HasArrived             int64          `json:"has_arrived"`
	CurrentStatus          interface{}    `json:"current_status"`
	LastKnownLatU6         sql.NullInt64  `json:"last_known_lat_u6"`
	LastKnownLngU6         sql.NullInt64  `json:"last_known_lng_u6"`
	LastKnownSnappedLatU6  sql.NullInt64  `json:"last_known_snapped_lat_u6"`
	LastKnownSnappedLngU6  sql.NullInt64  `json:"last_known_snapped_lng_u6"`
	LastRouteFracU4        sql.NullInt64  `json:"last_route_frac_u4"`
	LastKnownDistanceKmU4  sql.NullInt64  `json:"last_known_distance_km_u4"`
	LastUpdatedSno         sql.NullString `json:"last_updated_sno"`
	Errors                 db.RunErrors   `json:"errors"`
	LastUpdateTimestampIso sql.NullString `json:"last_update_timestamp_iso"`
	CreatedAt              string         `json:"created_at"`
	UpdatedAt              string         `json:"updated_at"`
}

type TrainRunLocation struct {
	ID                 int64         `json:"id"`
	RunID              string        `json:"run_id"`
	LatU6              int64         `json:"lat_u6"`
	LngU6              int64         `json:"lng_u6"`
	SnappedLatU6       sql.NullInt64 `json:"snapped_lat_u6"`
	SnappedLngU6       sql.NullInt64 `json:"snapped_lng_u6"`
	DistanceKmU4       int64         `json:"distance_km_u4"`
	SegmentStationCode string        `json:"segment_station_code"`
	AtStation          int64         `json:"at_station"`
	TimestampIso       string        `json:"timestamp_iso"`
}

type TrainSchedule struct {
	ScheduleID            int64          `json:"schedule_id"`
	TrainNo               int64          `json:"train_no"`
	OriginStationCode     string         `json:"origin_station_code"`
	TerminusStationCode   string         `json:"terminus_station_code"`
	OriginSchDepartureMin int64          `json:"origin_sch_departure_min"`
	TotalDistanceKm       float64        `json:"total_distance_km"`
	TotalRuntimeMin       int64          `json:"total_runtime_min"`
	RunningDaysBitmap     int64          `json:"running_days_bitmap"`
	CreatedAt             sql.NullString `json:"created_at"`
	UpdatedAt             sql.NullString `json:"updated_at"`
}
