// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
)

type Station struct {
	StationCode string         `json:"station_code"`
	StationName string         `json:"station_name"`
	Address     sql.NullString `json:"address"`
	ElevationM  float64        `json:"elevation_m"`
	Lat         float64        `json:"lat"`
	Lng         float64        `json:"lng"`
	CreatedAt   sql.NullString `json:"created_at"`
	UpdatedAt   sql.NullString `json:"updated_at"`
}

type Train struct {
	TrainNo   int64          `json:"train_no"`
	TrainName string         `json:"train_name"`
	TrainType string         `json:"train_type"`
	CreatedAt sql.NullString `json:"created_at"`
	UpdatedAt sql.NullString `json:"updated_at"`
}

type TrainRoute struct {
	ScheduleID               int64   `json:"schedule_id"`
	StationCode              string  `json:"station_code"`
	DistanceKm               float64 `json:"distance_km"`
	SchArrivalMinFromStart   int64   `json:"sch_arrival_min_from_start"`
	SchDepartureMinFromStart int64   `json:"sch_departure_min_from_start"`
	Stops                    int64   `json:"stops"`
}

type TrainRun struct {
	RunID                  string          `json:"run_id"`
	ScheduleID             int64           `json:"schedule_id"`
	TrainNo                int64           `json:"train_no"`
	RunDate                string          `json:"run_date"`
	HasStarted             int64           `json:"has_started"`
	HasArrived             int64           `json:"has_arrived"`
	EndReason              sql.NullString  `json:"end_reason"`
	LastKnownLat           sql.NullFloat64 `json:"last_known_lat"`
	LastKnownLng           sql.NullFloat64 `json:"last_known_lng"`
	LastUpdateTimestampIso sql.NullString  `json:"last_update_timestamp_iso"`
	Errors                 json.RawMessage `json:"errors"`
	CreatedAt              sql.NullString  `json:"created_at"`
	UpdatedAt              sql.NullString  `json:"updated_at"`
}

type TrainRunLocation struct {
	ID           int64   `json:"id"`
	RunID        string  `json:"run_id"`
	Lat          float64 `json:"lat"`
	Lng          float64 `json:"lng"`
	TimestampIso string  `json:"timestamp_iso"`
}

type TrainSchedule struct {
	ScheduleID            int64          `json:"schedule_id"`
	TrainNo               int64          `json:"train_no"`
	OriginStationCode     string         `json:"origin_station_code"`
	TerminusStationCode   string         `json:"terminus_station_code"`
	OriginSchDepartureMin int64          `json:"origin_sch_departure_min"`
	TerminusSchArrivalMin int64          `json:"terminus_sch_arrival_min"`
	TotalDistanceKm       float64        `json:"total_distance_km"`
	TotalRuntimeMin       int64          `json:"total_runtime_min"`
	RunningDaysBitmap     int64          `json:"running_days_bitmap"`
	CreatedAt             sql.NullString `json:"created_at"`
	UpdatedAt             sql.NullString `json:"updated_at"`
}
