// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries_api.sql

package db

import (
	"context"
	"database/sql"
)

const getTrainsInViewport = `-- name: GetTrainsInViewport :many
SELECT 
    tr.train_no,
    tr.last_known_snapped_lat_u6 AS lat_u6,
    tr.last_known_snapped_lng_u6 AS lng_u6,
    tr.last_bearing_deg AS bearing_deg,
    tr.current_status,
    tr.last_update_timestamp_iso,
    t.train_name,
    t.train_type
FROM train_runs tr
JOIN trains t ON tr.train_no = t.train_no
WHERE tr.has_arrived = 0
  AND tr.last_known_snapped_lat_u6 IS NOT NULL
  AND tr.last_known_snapped_lng_u6 IS NOT NULL
  -- Spatial bounds filter (with u6 encoding)
  AND tr.last_known_snapped_lat_u6 >= ?1
  AND tr.last_known_snapped_lat_u6 <= ?2
  AND tr.last_known_snapped_lng_u6 >= ?3
  AND tr.last_known_snapped_lng_u6 <= ?4
  -- Only recent updates (avoid stale data)
  AND datetime(tr.last_update_timestamp_iso) > datetime('now', '-10 minutes')
ORDER BY tr.last_update_timestamp_iso DESC
`

type GetTrainsInViewportParams struct {
	MinLatU6 sql.NullInt64 `json:"min_lat_u6"`
	MaxLatU6 sql.NullInt64 `json:"max_lat_u6"`
	MinLngU6 sql.NullInt64 `json:"min_lng_u6"`
	MaxLngU6 sql.NullInt64 `json:"max_lng_u6"`
}

type GetTrainsInViewportRow struct {
	TrainNo                int64          `json:"train_no"`
	LatU6                  sql.NullInt64  `json:"lat_u6"`
	LngU6                  sql.NullInt64  `json:"lng_u6"`
	BearingDeg             sql.NullInt64  `json:"bearing_deg"`
	CurrentStatus          interface{}    `json:"current_status"`
	LastUpdateTimestampIso sql.NullString `json:"last_update_timestamp_iso"`
	TrainName              string         `json:"train_name"`
	TrainType              string         `json:"train_type"`
}

// Returns data for active trains within viewport bounds
func (q *Queries) GetTrainsInViewport(ctx context.Context, arg GetTrainsInViewportParams) ([]GetTrainsInViewportRow, error) {
	rows, err := q.db.QueryContext(ctx, getTrainsInViewport,
		arg.MinLatU6,
		arg.MaxLatU6,
		arg.MinLngU6,
		arg.MaxLngU6,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTrainsInViewportRow{}
	for rows.Next() {
		var i GetTrainsInViewportRow
		if err := rows.Scan(
			&i.TrainNo,
			&i.LatU6,
			&i.LngU6,
			&i.BearingDeg,
			&i.CurrentStatus,
			&i.LastUpdateTimestampIso,
			&i.TrainName,
			&i.TrainType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
