// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: v1/api.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrainType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainType) Reset() {
	*x = TrainType{}
	mi := &file_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainType) ProtoMessage() {}

func (x *TrainType) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainType.ProtoReflect.Descriptor instead.
func (*TrainType) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *TrainType) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TrainType) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type TrainStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainStatus) Reset() {
	*x = TrainStatus{}
	mi := &file_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainStatus) ProtoMessage() {}

func (x *TrainStatus) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainStatus.ProtoReflect.Descriptor instead.
func (*TrainStatus) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *TrainStatus) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TrainStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type LiveTrain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrainNo       uint32                 `protobuf:"varint,1,opt,name=train_no,json=trainNo,proto3" json:"train_no,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TypeId        uint32                 `protobuf:"varint,3,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	LatU6         uint32                 `protobuf:"varint,4,opt,name=lat_u6,json=latU6,proto3" json:"lat_u6,omitempty"`
	LngU6         uint32                 `protobuf:"varint,5,opt,name=lng_u6,json=lngU6,proto3" json:"lng_u6,omitempty"`
	BearingDeg    uint32                 `protobuf:"varint,6,opt,name=bearing_deg,json=bearingDeg,proto3" json:"bearing_deg,omitempty"`
	StatusId      uint32                 `protobuf:"varint,7,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveTrain) Reset() {
	*x = LiveTrain{}
	mi := &file_v1_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveTrain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveTrain) ProtoMessage() {}

func (x *LiveTrain) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveTrain.ProtoReflect.Descriptor instead.
func (*LiveTrain) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{2}
}

func (x *LiveTrain) GetTrainNo() uint32 {
	if x != nil {
		return x.TrainNo
	}
	return 0
}

func (x *LiveTrain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LiveTrain) GetTypeId() uint32 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *LiveTrain) GetLatU6() uint32 {
	if x != nil {
		return x.LatU6
	}
	return 0
}

func (x *LiveTrain) GetLngU6() uint32 {
	if x != nil {
		return x.LngU6
	}
	return 0
}

func (x *LiveTrain) GetBearingDeg() uint32 {
	if x != nil {
		return x.BearingDeg
	}
	return 0
}

func (x *LiveTrain) GetStatusId() uint32 {
	if x != nil {
		return x.StatusId
	}
	return 0
}

type LiveTrainsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []*TrainStatus         `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	Types         []*TrainType           `protobuf:"bytes,2,rep,name=types,proto3" json:"types,omitempty"`
	Trains        []*LiveTrain           `protobuf:"bytes,3,rep,name=trains,proto3" json:"trains,omitempty"`
	Total         uint32                 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Timestamp     string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveTrainsResponse) Reset() {
	*x = LiveTrainsResponse{}
	mi := &file_v1_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveTrainsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveTrainsResponse) ProtoMessage() {}

func (x *LiveTrainsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveTrainsResponse.ProtoReflect.Descriptor instead.
func (*LiveTrainsResponse) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{3}
}

func (x *LiveTrainsResponse) GetStatuses() []*TrainStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *LiveTrainsResponse) GetTypes() []*TrainType {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *LiveTrainsResponse) GetTrains() []*LiveTrain {
	if x != nil {
		return x.Trains
	}
	return nil
}

func (x *LiveTrainsResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *LiveTrainsResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type TrainRun struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	TrainNo       int64                  `protobuf:"varint,2,opt,name=train_no,json=trainNo,proto3" json:"train_no,omitempty"`
	RunDate       string                 `protobuf:"bytes,3,opt,name=run_date,json=runDate,proto3" json:"run_date,omitempty"`
	HasStarted    bool                   `protobuf:"varint,4,opt,name=has_started,json=hasStarted,proto3" json:"has_started,omitempty"`
	HasArrived    bool                   `protobuf:"varint,5,opt,name=has_arrived,json=hasArrived,proto3" json:"has_arrived,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	LatU6         int32                  `protobuf:"varint,7,opt,name=lat_u6,json=latU6,proto3" json:"lat_u6,omitempty"`
	LngU6         int32                  `protobuf:"varint,8,opt,name=lng_u6,json=lngU6,proto3" json:"lng_u6,omitempty"`
	BearingDeg    int32                  `protobuf:"varint,9,opt,name=bearing_deg,json=bearingDeg,proto3" json:"bearing_deg,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainRun) Reset() {
	*x = TrainRun{}
	mi := &file_v1_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainRun) ProtoMessage() {}

func (x *TrainRun) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainRun.ProtoReflect.Descriptor instead.
func (*TrainRun) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{4}
}

func (x *TrainRun) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *TrainRun) GetTrainNo() int64 {
	if x != nil {
		return x.TrainNo
	}
	return 0
}

func (x *TrainRun) GetRunDate() string {
	if x != nil {
		return x.RunDate
	}
	return ""
}

func (x *TrainRun) GetHasStarted() bool {
	if x != nil {
		return x.HasStarted
	}
	return false
}

func (x *TrainRun) GetHasArrived() bool {
	if x != nil {
		return x.HasArrived
	}
	return false
}

func (x *TrainRun) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TrainRun) GetLatU6() int32 {
	if x != nil {
		return x.LatU6
	}
	return 0
}

func (x *TrainRun) GetLngU6() int32 {
	if x != nil {
		return x.LngU6
	}
	return 0
}

func (x *TrainRun) GetBearingDeg() int32 {
	if x != nil {
		return x.BearingDeg
	}
	return 0
}

func (x *TrainRun) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_v1_api_proto protoreflect.FileDescriptor

const file_v1_api_proto_rawDesc = "" +
	"\n" +
	"\fv1/api.proto\x12\ftrano.api.v1\"/\n" +
	"\tTrainType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"5\n" +
	"\vTrainStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xbf\x01\n" +
	"\tLiveTrain\x12\x19\n" +
	"\btrain_no\x18\x01 \x01(\rR\atrainNo\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\atype_id\x18\x03 \x01(\rR\x06typeId\x12\x15\n" +
	"\x06lat_u6\x18\x04 \x01(\rR\x05latU6\x12\x15\n" +
	"\x06lng_u6\x18\x05 \x01(\rR\x05lngU6\x12\x1f\n" +
	"\vbearing_deg\x18\x06 \x01(\rR\n" +
	"bearingDeg\x12\x1b\n" +
	"\tstatus_id\x18\a \x01(\rR\bstatusId\"\xdf\x01\n" +
	"\x12LiveTrainsResponse\x125\n" +
	"\bstatuses\x18\x01 \x03(\v2\x19.trano.api.v1.TrainStatusR\bstatuses\x12-\n" +
	"\x05types\x18\x02 \x03(\v2\x17.trano.api.v1.TrainTypeR\x05types\x12/\n" +
	"\x06trains\x18\x03 \x03(\v2\x17.trano.api.v1.LiveTrainR\x06trains\x12\x14\n" +
	"\x05total\x18\x04 \x01(\rR\x05total\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\"\x9f\x02\n" +
	"\bTrainRun\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x19\n" +
	"\btrain_no\x18\x02 \x01(\x03R\atrainNo\x12\x19\n" +
	"\brun_date\x18\x03 \x01(\tR\arunDate\x12\x1f\n" +
	"\vhas_started\x18\x04 \x01(\bR\n" +
	"hasStarted\x12\x1f\n" +
	"\vhas_arrived\x18\x05 \x01(\bR\n" +
	"hasArrived\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x15\n" +
	"\x06lat_u6\x18\a \x01(\x05R\x05latU6\x12\x15\n" +
	"\x06lng_u6\x18\b \x01(\x05R\x05lngU6\x12\x1f\n" +
	"\vbearing_deg\x18\t \x01(\x05R\n" +
	"bearingDeg\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAtB\x1eZ\x1ctrano/internal/api/schema/v1b\x06proto3"

var (
	file_v1_api_proto_rawDescOnce sync.Once
	file_v1_api_proto_rawDescData []byte
)

func file_v1_api_proto_rawDescGZIP() []byte {
	file_v1_api_proto_rawDescOnce.Do(func() {
		file_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_api_proto_rawDesc), len(file_v1_api_proto_rawDesc)))
	})
	return file_v1_api_proto_rawDescData
}

var file_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_v1_api_proto_goTypes = []any{
	(*TrainType)(nil),          // 0: trano.api.v1.TrainType
	(*TrainStatus)(nil),        // 1: trano.api.v1.TrainStatus
	(*LiveTrain)(nil),          // 2: trano.api.v1.LiveTrain
	(*LiveTrainsResponse)(nil), // 3: trano.api.v1.LiveTrainsResponse
	(*TrainRun)(nil),           // 4: trano.api.v1.TrainRun
}
var file_v1_api_proto_depIdxs = []int32{
	1, // 0: trano.api.v1.LiveTrainsResponse.statuses:type_name -> trano.api.v1.TrainStatus
	0, // 1: trano.api.v1.LiveTrainsResponse.types:type_name -> trano.api.v1.TrainType
	2, // 2: trano.api.v1.LiveTrainsResponse.trains:type_name -> trano.api.v1.LiveTrain
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_api_proto_init() }
func file_v1_api_proto_init() {
	if File_v1_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_api_proto_rawDesc), len(file_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_api_proto_goTypes,
		DependencyIndexes: file_v1_api_proto_depIdxs,
		MessageInfos:      file_v1_api_proto_msgTypes,
	}.Build()
	File_v1_api_proto = out.File
	file_v1_api_proto_goTypes = nil
	file_v1_api_proto_depIdxs = nil
}
